name: Compilar Sentinel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar CMake
        run: cmake -B build -S .

      - name: Compilar
        run: cmake --build build

      - name: Ejecutar tests
        run: ctest --test-dir build --output-on-failure

      # --- DESPLIEGUE EN EL SERVIDOR ---
      - name: Transferir proyecto al servidor
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_deploy -o StrictHostKeyChecking=no" \
            --exclude '.git' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/deploy/sentinel-deploy/

      - name: Ejecutar instalación remota servidor
        run: |
          ssh -i ~/.ssh/id_deploy -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            sudo /home/deploy/sentinel-deploy/scripts/install.sh --server sentinel "

      - name: Eliminar carpeta build servidor
        run: |
          ssh -i ~/.ssh/id_deploy -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          rm -rf /home/deploy/sentinel-deploy/build "

      # --- DESPLIEGUE EN EL ESCRITORIO ---
      - name: Transferir proyecto a escritorio
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_deploy_escritorio -o StrictHostKeyChecking=no" \
            --exclude '.git' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.DESKTOP_IP }}:/home/deploy/sentinel-deploy/

      - name: Ejecutar instalación remota a escritorio
        run: |
          ssh -i ~/.ssh/id_deploy_escritorio -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.DESKTOP_IP }} "sudo /home/deploy/sentinel-deploy/scripts/install.sh --desktop ${{ secrets.USER_NAME }}"

      - name: Eliminar carpeta build escritorio
        run: |
          ssh -i ~/.ssh/id_deploy_escritorio -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.DESKTOP_IP }} "rm -rf /home/deploy/sentinel-deploy/build"
