name: Compilar Sentinel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar CMake
        run: cmake -B build -S .

      - name: Compilar
        run: cmake --build build

      - name: Ejecutar tests
        run: ctest --test-dir build --output-on-failure

      - name: Confirmar que el binario existe
        run: |
          if [ -f build/sentinel ]; then
            echo "Compilación exitosa"
          else
            echo "No se encontró el binario esperado"
            exit 1
          fi

      - name: Transferir proyecto al servidor
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git' \
            ./ deploy@192.168.1.11:/home/deploy/sentinel-deploy/

      - name: Ejecutar instalación remota
        run: |
          ssh -o StrictHostKeyChecking=no deploy@192.168.1.11 "
            sudo /home/deploy/sentinel-deploy/scripts/install.sh --server sentinel "

      - name: Eliminar carpeta build servidor
        run: |
          ssh -o StrictHostKeyChecking=no deploy@192.168.1.11 "
          rm -rf /home/deploy/sentinel-deploy/build "

      - name: Transferir proyecto a escritorio
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git' \
            ./ deploy@192.168.1.4:/home/deploy/sentinel-deploy/

      - name: Ejecutar instalación remota a escritorio
        run: |
          ssh -o StrictHostKeyChecking=no deploy@192.168.1.6 "
            sudo /home/deploy/sentinel-deploy/scripts/install.sh --desktop Emerson "

      - name: Eliminar carpeta build escritorio
        run: |
          ssh -o StrictHostKeyChecking=no deploy@192.168.1.6 "
          rm -rf /home/deploy/sentinel-deploy/build "